language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
# command to install dependencies
before_install:
  - pip install codecov
after_success:
  - codecov
install:
    - "pip install -r requirements.txt"
    - "make install"
# # command to run tests
script: make tests
notifications:
    webhooks:
    urls:
        - https://webhooks.gitter.im/e/1783c332a0ad247e3476
    on_success: always
    on_failure: always
    on_start: false
